version: 0.2.7.build{build}

image: Visual Studio 2019

clone_folder: C:\projects\welsonjs

environment:
  ORGANIZATION_ID: 8ee5ec82-36dc-4619-ac33-5bc1117428fe
  PROJECT_SLUG: welsonjs
  ARTIFACT_CONFIGURATION_SLUG: initial
  matrix:
    - CONFIGURATION: Debug
      SIGNING_POLICY_SLUG: test-signing
    - CONFIGURATION: Release
      SIGNING_POLICY_SLUG: release-signing

before_build:
  - nuget restore WelsonJS.Toolkit

build_script:
  - msbuild "C:\projects\welsonjs\WelsonJS.Toolkit\WelsonJS.Toolkit.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=%CONFIGURATION% /p:Platform="x86"

#after_build:
#  - cmd: 7z a WelsonJS.Toolkit.zip WelsonJS.Toolkit\WelsonJS.Toolkit\bin\x86\%CONFIGURATION%\*
#  - cmd: 7z a WelsonJS.Service.zip WelsonJS.Toolkit\WelsonJS.Service\bin\x86\%CONFIGURATION%\*
#  - cmd: 7z a WelsonJS.Launcher.zip WelsonJS.Toolkit\WelsonJS.Launcher\bin\x86\%CONFIGURATION%\*

after_build:
  - cmd: 7z a WelsonJS.Toolkit.zip WelsonJS.Toolkit\WelsonJS.Service\bin\x86\%CONFIGURATION%\* WelsonJS.Toolkit\WelsonJS.Launcher\bin\x86\%CONFIGURATION%\*

artifacts:
  - path: WelsonJS.Toolkit.zip
    name: WelsonJS.Toolkit

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/%ORGANIZATION_ID%/Integrations/AppVeyor?ProjectSlug=%PROJECT_SLUG%&SigningPolicySlug=%SIGNING_POLICY_SLUG%&ArtifactConfigurationSlug=%ARTIFACT_CONFIGURATION_SLUG%
  authorization:
    secure: nABfe+lksIRfS7lVnkq3EdIYNH8KOka+5ZFTUJqUW2nckBubhrlAXarbCPJHLp9FWWf3zxAWhNwT0It+qyqPRQ==

notifications:
  - provider: Email
    to:
      - abuse@catswords.net
    subject: 'Build #{{build}} {{status}}'
    on_build_success: false
    on_build_failure: true
