version: 0.2.7.build{build}

image: Visual Studio 2019

clone_folder: C:\projects\welsonjs

environment:
  matrix:
    - CONFIGURATION: Debug
    - CONFIGURATION: Release

build_script:
  - msbuild "C:\projects\welsonjs\WelsonJS.Toolkit\WelsonJS.Toolkit.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=%CONFIGURATION% /p:Platform="x86"
  - msbuild "C:\projects\welsonjs\WelsonJS.Toolkit\WelsonJS.Toolkit.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=%CONFIGURATION% /p:Platform="x64"

artifacts:
  - path: WelsonJS.Toolkit\WelsonJS.Toolkit\bin\x86\WelsonJS.Toolkit.dll
    name: WelsonJS.Toolkit.x86
  - path: WelsonJS.Toolkit\WelsonJS.Toolkit\bin\x64\WelsonJS.Toolkit.dll
    name: WelsonJS.Toolkit.x64
  - path: WelsonJS.Toolkit\WelsonJS.Service\bin\x86\WelsonJS.Service.exe
    name: WelsonJS.Service

notifications:
  - provider: Email
    to:
      - abuse@catswords.net
    subject: 'Build #{build} {status}'
    on_build_success: true
    on_build_failure: true